config/routes.rb
GoalSetterApp::Application.routes.draw do

  root to: 'sessions#new'

  put 'goals/:id/complete' => 'goals#complete', as: "goal_completion"

  resources :users, :only => [:index, :new, :create, :show, :destroy] do
    resources :goals, :only => [:create]
  end
  resource :session, :only => [:new, :create, :destroy]
  resources :goals, :only => [:edit, :update, :destroy]
end

app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id           :integer          not null, primary key
#  title        :string(255)      not null
#  body         :text
#  author_id    :integer          not null
#  is_private   :boolean          default(FALSE), not null
#  is_completed :boolean          default(FALSE), not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Goal < ActiveRecord::Base
  attr_accessible :title, :body, :author_id, :is_private

  validates :title, :author, presence: true
  validates :is_completed, :is_private, inclusion: { in: [true, false] }, allow_nil: true

  belongs_to :author, class_name: "User", foreign_key: :author_id, inverse_of: :goals

  def private?
    self.is_private
  end

  def completed?
    self.is_completed
  end

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string(255)      not null
#  password_digest :string(255)      not null
#  session_token   :string(255)      not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  admin           :boolean          default(FALSE), not null
#

class User < ActiveRecord::Base
  attr_accessible :username, :password
  attr_reader :password

  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  before_validation :ensure_session_token

  has_many :goals, class_name: "Goal", foreign_key: :author_id, inverse_of: :author

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    return nil if user.nil?

    user.correct_password?(password) ? user : nil
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
  end

  def correct_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def admin?
    self.admin
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  def current_user
    return nil unless session[:session_token]
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def log_in(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def log_out!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def authenticate
    redirect_to new_session_url unless logged_in?
  end

  def require_admin_privilege
    unless current_user.admin?
      session[:session_token] = nil
      redirect_to new_session_url
    end
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  def create
    goal = current_user.goals.new(params[:goal])

    flash[:errors] = goal.errors.full_messages unless goal.save
    redirect_to user_url(current_user)
  end

  def edit
    @goal = current_user.goals.find(params[:id])
    render :edit
  end

  def update
    @goal = current_user.goals.find(params[:id])

    if @goal.update_attributes(params[:goal])
      redirect_to user_url(current_user)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def destroy
    goal = current_user.goals.find(params[:id])

    goal.destroy
    redirect_to user_url(goal.author)
  end

  def complete
    goal = current_user.goals.find(params[:id])

    goal.is_completed = true
    goal.save!

    redirect_to user_url(goal.author)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    render :new
  end

  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password])

    if user.nil?
      flash[:errors] = ["Incorrect credentials"]
      redirect_to new_session_url
    else
      log_in(user)
      redirect_to user_url(user)
    end
  end

  def destroy
    log_out!
    redirect_to new_session_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_admin_privilege, :only => :destroy
  before_filter :authenticate, :except => [:new, :create]

  def index
    @users = User.all
    render :index
  end

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      log_in(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.includes(:goals).find(params[:id])
    render :show
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_url
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    "<input
      type=\"hidden\"
      name=\"authenticity_token\"
      value=\"#{form_authenticity_token}\">".html_safe
  end

  def can_delete?(user)
    current_user.id == user.id || current_user.admin?
  end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/edit.html.erb
<h1>Edit Goal</h1>

<form action="<%= goal_url(@goal) %>" method="post">
  <input type="hidden" name="_method" value="put">

  <%= auth_token %>

  <label>Title
    <input type="text" name="goal[title]" value="<%= @goal.title %>">
  </label>

  <label>Description
    <textarea name="goal[body]" value="<%= @goal.body %>"></textarea>
  </label>

  <label>Privacy
    <input type="radio" name="goal[is_private]"
      <%="checked" if @goal.private? %>>
  </label>

  <input type="submit" value="Update Goal">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalSetterApp</title>
</head>
<body>
  <%= flash[:errors].join('<br>').html_safe if flash[:errors] %>

  <% if current_user %>
    You are signed in as
    <%= current_user.username %><br>
    <%= button_to "Sign Out", session_url, :method => :delete %>

  <% else %>
    <%= link_to "Sign Up", new_user_url %>
    <%= link_to "Sign In", new_session_url %>

  <% end %>

<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<h2> All users </h2>

<ul>
  <% @users.each do |user| %>
  <li>
    <%= link_to user.username, user_url(user) %>
    <% if current_user.admin? %>
      <%= button_to "Delete User", user_url(user), :method => :delete %>
    <% end %>
  </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="post">
  <%= auth_token %>

  <label>Username
    <input type="text" name="user[username]" value="">
  </label>

  <label>Password
    <input type="password" name="user[password]" value="">
  </label>

  <input type="submit" value="Sign Up">

</form>

app/views/users/show.html.erb
<h2><%= @user.username.capitalize %>'s Goals</h2>

<form action="<%= user_goals_url(@user) %>" method="post">
  <%= auth_token %>

  <label>Title
    <input type="text" name="goal[title]">
  </label><br>

  <label>Description
    <textarea name="goal[body]"></textarea>
  </label><br>

  <label>Private?
    <input type="radio" name="goal[is_private]">
  </label><br>

  <input type="submit" value="Add Goal">
</form>

<table>
  <tr>
    <th> Title </th>
    <th width="100"> Description </th>
    <th> Privacy </th>
    <th> Status </th>
    <th></th>
  </tr>

  <% @user.goals.each do |goal| %>
    <% next if goal.private? && (current_user.id != @user.id || !curent.user.admin?) %>
    <tr>
      <td> <%= goal.title %> </td>
      <td> <%= goal.body %></td>
      <td> <%= goal.private? ? "Private" : "Public" %></td>
      <td> <%= goal.completed? ? "Complete" : "Incomplete" %></td>

      <% if can_delete?(@user) %>
        <td>
          <%= button_to "Delete Goal", goal_url(goal), method: :delete %>
        </td>
      <% end %>

      <% if current_user.id == @user.id %>
        <td>
          <%= link_to "Edit Goal", edit_goal_url(goal) %>
        </td>
      <% end %>

      <% if current_user.id == @user.id && !goal.completed? %>
        <td>
          <%= button_to "Complete",
            goal_completion_url(goal),
            method: :put %>
        </td>
      <% end %>
    </tr>
  <% end %>

</table>